; stringToUri.ahk
; Version 0.002

#Requires AutoHotkey v2

stringToUri(s, complete := 0){
  convertMap := Map()
  if (complete){
    convertMap.Set("0", "%30")
    convertMap.Set("1", "%31")
    convertMap.Set("2", "%32")
    convertMap.Set("3", "%33")
    convertMap.Set("4", "%34")
    convertMap.Set("5", "%35")
    convertMap.Set("6", "%36")
    convertMap.Set("7", "%37")
    convertMap.Set("8", "%38")
    convertMap.Set("9", "%39")
    convertMap.Set("A", "%41")
    convertMap.Set("B", "%42")
    convertMap.Set("C", "%43")
    convertMap.Set("D", "%44")
    convertMap.Set("E", "%45")
    convertMap.Set("F", "%46")
    convertMap.Set("G", "%47")
    convertMap.Set("H", "%48")
    convertMap.Set("I", "%49")
    convertMap.Set("J", "%4A")
    convertMap.Set("K", "%4B")
    convertMap.Set("L", "%4C")
    convertMap.Set("M", "%4D")
    convertMap.Set("N", "%4E")
    convertMap.Set("O", "%4F")
    convertMap.Set("P", "%50")
    convertMap.Set("Q", "%51")
    convertMap.Set("R", "%52")
    convertMap.Set("S", "%53")
    convertMap.Set("T", "%54")
    convertMap.Set("U", "%55")
    convertMap.Set("V", "%56")
    convertMap.Set("W", "%57")
    convertMap.Set("X", "%58")
    convertMap.Set("Y", "%59")
    convertMap.Set("Z", "%5A")
    convertMap.Set("a", "%61")
    convertMap.Set("b", "%62")
    convertMap.Set("c", "%63")
    convertMap.Set("d", "%64")
    convertMap.Set("e", "%65")
    convertMap.Set("f", "%66")
    convertMap.Set("g", "%67")
    convertMap.Set("h", "%68")
    convertMap.Set("i", "%69")
    convertMap.Set("j", "%6A")
    convertMap.Set("k", "%6B")
    convertMap.Set("l", "%6C")
    convertMap.Set("m", "%6D")
    convertMap.Set("n", "%6E")
    convertMap.Set("o", "%6F")
    convertMap.Set("p", "%70")
    convertMap.Set("q", "%71")
    convertMap.Set("r", "%72")
    convertMap.Set("s", "%73")
    convertMap.Set("t", "%74")
    convertMap.Set("u", "%75")
    convertMap.Set("v", "%76")
    convertMap.Set("w", "%77")
    convertMap.Set("x", "%78")
    convertMap.Set("y", "%79")
    convertMap.Set("z", "%7A")
  }
  
  convertMap.Set(" ", "%20")
  convertMap.Set("!", "%21")
  convertMap.Set("`"", "%22")
  convertMap.Set("#", "%23")
  convertMap.Set("$", "%24")
  convertMap.Set("%", "%25")
  convertMap.Set("&", "%26")
  convertMap.Set("'", "%27")
  convertMap.Set("(", "%28")
  convertMap.Set(")", "%29")
  convertMap.Set("*", "%2A")
  convertMap.Set("+", "%2B")
  convertMap.Set(",", "%2C")
  convertMap.Set("-", "%2D")
  convertMap.Set(".", "%2E")
  convertMap.Set("/", "%2F")

  convertMap.Set(":", "%3A")
  convertMap.Set("", "%3B")
  convertMap.Set("<", "%3C")
  convertMap.Set("=", "%3D")
  convertMap.Set(">", "%3E")
  convertMap.Set("?", "%3F")
  convertMap.Set("@", "%40")

  convertMap.Set("[", "%5B")
  convertMap.Set("\", "%5C")
  convertMap.Set("]", "%5D")
  convertMap.Set("^", "%5E")
  convertMap.Set("_", "%5F")
  convertMap.Set("``", "%60")

  convertMap.Set("{", "%7B")
  convertMap.Set("|", "%7C")
  convertMap.Set("}", "%7D")
  convertMap.Set("~", "%7E")
  convertMap.Set(Chr(8239), "%7F")
  convertMap.Set("€", "%E2%82%AC")
  convertMap.Set("", "%81")
  convertMap.Set("‚", "%E2%80%9A")
  convertMap.Set("ƒ", "%C6%92")
  convertMap.Set("„", "%E2%80%9E")
  convertMap.Set("…", "%E2%80%A6")
  convertMap.Set("†", "%E2%80%A0")
  convertMap.Set("‡", "%E2%80%A1")
  convertMap.Set("ˆ", "%CB%86")
  convertMap.Set("‰", "%E2%80%B0")
  convertMap.Set("Š", "%C5%A0")
  convertMap.Set("‹", "%E2%80%B9")
  convertMap.Set("Œ", "%C5%92")
  convertMap.Set("", "%C5%8D")
  convertMap.Set("Ž", "%C5%BD")
  convertMap.Set("", "%8F")
  convertMap.Set("", "%C2%90")
  convertMap.Set("‘", "%E2%80%98")
  convertMap.Set("’", "%E2%80%99")
  convertMap.Set("“", "%E2%80%9C")
  convertMap.Set("”", "%E2%80%9D")
  convertMap.Set("•", "%E2%80%A2")
  convertMap.Set("–", "%E2%80%93")
  convertMap.Set("—", "%E2%80%94")
  convertMap.Set("˜", "%CB%9C")
  convertMap.Set("™", "%E2%84")
  convertMap.Set("š", "%C5%A1")
  convertMap.Set("›", "%E2%80")
  convertMap.Set("œ", "%C5%93")
  convertMap.Set("", "%9D")
  convertMap.Set("ž", "%C5%BE")
  convertMap.Set("Ÿ", "%C5%B8")
  convertMap.Set(" ", "%C2%A0")
  convertMap.Set("¡", "%C2%A1")
  convertMap.Set("¢", "%C2%A2")
  convertMap.Set("£", "%C2%A3")
  convertMap.Set("¤", "%C2%A4")
  convertMap.Set("¥", "%C2%A5")
  convertMap.Set("¦", "%C2%A6")
  convertMap.Set("§", "%C2%A7")
  convertMap.Set("¨", "%C2%A8")
  convertMap.Set("©", "%C2%A9")
  convertMap.Set("ª", "%C2%AA")
  convertMap.Set("«", "%C2%AB")
  convertMap.Set("¬", "%C2%AC")
  convertMap.Set("Chr(173)", "%C2%AD")
  convertMap.Set("®", "%C2%AE")
  convertMap.Set("¯", "%C2%AF")
  convertMap.Set("°", "%C2%B0")
  convertMap.Set("±", "%C2%B1")
  convertMap.Set("²", "%C2%B2")
  convertMap.Set("³", "%C2%B3")
  convertMap.Set("´", "%C2%B4")
  convertMap.Set("µ", "%C2%B5")
  convertMap.Set("¶", "%C2%B6")
  convertMap.Set("·", "%C2%B7")
  convertMap.Set("¸", "%C2%B8")
  convertMap.Set("¹", "%C2%B9")
  convertMap.Set("º", "%C2%BA")
  convertMap.Set("»", "%C2%BB")
  convertMap.Set("¼", "%C2%BC")
  convertMap.Set("½", "%C2%BD")
  convertMap.Set("¾", "%C2%BE")
  convertMap.Set("¿", "%C2%BF")
  convertMap.Set("À", "%C3%80")
  convertMap.Set("Á", "%C3%81")
  convertMap.Set("Â", "%C3%82")
  convertMap.Set("Ã", "%C3%83")
  convertMap.Set("Ä", "%C3%84")
  convertMap.Set("Å", "%C3%85")
  convertMap.Set("Æ", "%C3%86")
  convertMap.Set("Ç", "%C3%87")
  convertMap.Set("È", "%C3%88")
  convertMap.Set("É", "%C3%89")
  convertMap.Set("Ê", "%C3%8A")
  convertMap.Set("Ë", "%C3%8B")
  convertMap.Set("Ì", "%C3%8C")
  convertMap.Set("Í", "%C3%8D")
  convertMap.Set("Î", "%C3%8E")
  convertMap.Set("Ï", "%C3%8F")
  convertMap.Set("Ð", "%C3%90")
  convertMap.Set("Ñ", "%C3%91")
  convertMap.Set("Ò", "%C3%92")
  convertMap.Set("Ó", "%C3%93")
  convertMap.Set("Ô", "%C3%94")
  convertMap.Set("Õ", "%C3%95")
  convertMap.Set("Ö", "%C3%96")
  convertMap.Set("×", "%C3%97")
  convertMap.Set("Ø", "%C3%98")
  convertMap.Set("Ù", "%C3%99")
  convertMap.Set("Ú", "%C3%9A")
  convertMap.Set("Û", "%C3%9B")
  convertMap.Set("Ü", "%C3%9C")
  convertMap.Set("Ý", "%C3%9D")
  convertMap.Set("Þ", "%C3%9E")
  convertMap.Set("ß", "%C3%9F")
  convertMap.Set("à", "%C3%A0")
  convertMap.Set("á", "%C3%A1")
  convertMap.Set("â", "%C3%A2")
  convertMap.Set("ã", "%C3%A3")
  convertMap.Set("ä", "%C3%A4")
  convertMap.Set("å", "%C3%A5")
  convertMap.Set("æ", "%C3%A6")
  convertMap.Set("ç", "%C3%A7")
  convertMap.Set("è", "%C3%A8")
  convertMap.Set("é", "%C3%A9")
  convertMap.Set("ê", "%C3%AA")
  convertMap.Set("ë", "%C3%AB")
  convertMap.Set("ì", "%C3%AC")
  convertMap.Set("í", "%C3%AD")
  convertMap.Set("î", "%C3%AE")
  convertMap.Set("ï", "%C3%AF")
  convertMap.Set("ð", "%C3%B0")
  convertMap.Set("ñ", "%C3%B1")
  convertMap.Set("ò", "%C3%B2")
  convertMap.Set("ó", "%C3%B3")
  convertMap.Set("ô", "%C3%B4")
  convertMap.Set("õ", "%C3%B5")
  convertMap.Set("ö", "%C3%B6")
  convertMap.Set("÷", "%C3%B7")
  convertMap.Set("ø", "%C3%B8")
  convertMap.Set("ù", "%C3%B9")
  convertMap.Set("ú", "%C3%BA")
  convertMap.Set("û", "%C3%BB")
  convertMap.Set("ü", "%C3%BC")
  convertMap.Set("ý", "%C3%BD")
  convertMap.Set("þ", "%C3%BE")
  convertMap.Set("ÿ", "%C3%BF")
  convertMap.Set("", "%01")
  convertMap.Set("", "%02")
  convertMap.Set("", "%03")
  convertMap.Set("", "%04")
  convertMap.Set("", "%05")
  convertMap.Set("", "%06")
  convertMap.Set("", "%07")
  convertMap.Set("", "%08")
  convertMap.Set("`t", "%09")
  convertMap.Set("`n", "%0A")
  convertMap.Set("", "%0B")
  convertMap.Set("", "%0C")
  convertMap.Set("`r", "%0D")
  convertMap.Set("", "%0E")
  convertMap.Set("", "%0F")
  convertMap.Set("", "%10")
  convertMap.Set("", "%11")
  convertMap.Set("", "%12")
  convertMap.Set("", "%13")
  convertMap.Set("", "%14")
  convertMap.Set("", "%15")
  convertMap.Set("", "%16")
  convertMap.Set("", "%17")
  convertMap.Set("", "%18")
  convertMap.Set("", "%19")
  convertMap.Set("", "%1A")
  convertMap.Set("", "%1B")
  convertMap.Set("", "%1C")
  convertMap.Set("", "%1D")
  convertMap.Set("", "%1E")
  convertMap.Set("", "%1F")
  convertMap.Set("", "%7F")
  convertMap.Set("", "%80")
  convertMap.Set("", "%81")
  convertMap.Set("", "%82")
  convertMap.Set("", "%83")
  convertMap.Set("", "%84")
  convertMap.Set("", "%85")
  convertMap.Set("", "%86")
  convertMap.Set("", "%87")
  convertMap.Set("", "%88")
  convertMap.Set("", "%89")
  convertMap.Set("", "%8A")
  convertMap.Set("", "%8B")
  convertMap.Set("", "%8C")
  convertMap.Set("", "%8D")
  convertMap.Set("", "%8E")
  convertMap.Set("", "%8F")
  convertMap.Set("", "%90")
  convertMap.Set("", "%91")
  convertMap.Set("", "%92")
  convertMap.Set("", "%93")
  convertMap.Set("", "%94")
  convertMap.Set("", "%95")
  convertMap.Set("", "%96")
  convertMap.Set("", "%97")
  convertMap.Set("", "%98")
  convertMap.Set("", "%99")
  convertMap.Set("", "%9A")
  convertMap.Set("", "%9B")
  convertMap.Set("", "%9C")
  convertMap.Set("", "%9D")
  convertMap.Set("", "%9E")
  convertMap.Set("", "%9F")

  ret := ""

  Loop Parse s {
    if (convertMap.Has(A_Loopfield)){
      ret .= convertMap.Get(A_Loopfield)
    } else {
      ret .= A_Loopfield
    }
  }

  return ret
}




